version: "3"
services:
  app:
    container_name: smart-manager
    restart: always
    build: .
    ports:
      - "8080:80"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"